import type { Product, Category } from '@/types';
import { CATEGORIES } from '@/constants/categories';

// Helper to generate product slug
const generateSlug = (name: string): string =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

// Helper to get category info
const getCategory = (categoryId: string): Pick<Category, 'id' | 'name' | 'slug'> => {
  const cat = CATEGORIES.find((c) => c.id === categoryId);
  return cat
    ? { id: cat.id, name: cat.name, slug: cat.slug }
    : { id: categoryId, name: categoryId, slug: categoryId };
};

export const mockProducts: Product[] = [
  // CHANDELIERS (8 products)
  {
    id: 'ch-001',
    sku: 'NJE-CH-001',
    name: 'Crystal Chandelier 8-Light Modern',
    slug: 'crystal-chandelier-8-light-modern',
    description: 'Elegant 8-light crystal chandelier with premium K9 crystals and chrome finish. Perfect for living rooms, dining areas, and hotel lobbies. Creates stunning light reflections.',
    price: 45000,
    compareAtPrice: 55000,
    categoryId: 'chandeliers',
    category: getCategory('chandeliers'),
    images: [
      'https://images.unsplash.com/photo-1543198126-a8ad8e47fb22?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'K9 Crystal + Chrome',
      'Bulb Type': 'E14 x 8',
      'Wattage': '40W per bulb',
      'Diameter': '80cm',
      'Height': '60cm',
      'Chain Length': '50cm (adjustable)',
    },
    stock: 5,
    lowStockThreshold: 2,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'ch-002',
    sku: 'NJE-CH-002',
    name: 'Gold Branch Chandelier 6-Arm',
    slug: 'gold-branch-chandelier-6-arm',
    description: 'Contemporary gold branch design chandelier with 6 arms. Frosted glass shades provide soft, ambient lighting. Ideal for modern interiors.',
    price: 38000,
    categoryId: 'chandeliers',
    category: getCategory('chandeliers'),
    images: [
      'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'Iron + Frosted Glass',
      'Finish': 'Gold',
      'Bulb Type': 'E27 x 6',
      'Diameter': '70cm',
      'Height': '50cm',
    },
    stock: 8,
    lowStockThreshold: 3,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'ch-003',
    sku: 'NJE-CH-003',
    name: 'Mini Crystal Chandelier 3-Light',
    slug: 'mini-crystal-chandelier-3-light',
    description: 'Compact crystal chandelier perfect for bedrooms, hallways, and small spaces. Beautiful crystal drops create elegant ambiance.',
    price: 15000,
    compareAtPrice: 18000,
    categoryId: 'chandeliers',
    category: getCategory('chandeliers'),
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'Crystal + Chrome',
      'Bulb Type': 'E14 x 3',
      'Diameter': '35cm',
      'Height': '30cm',
    },
    stock: 15,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'ch-004',
    sku: 'NJE-CH-004',
    name: 'Black Iron Industrial Chandelier',
    slug: 'black-iron-industrial-chandelier',
    description: 'Industrial-style black iron chandelier with exposed bulbs. Perfect for restaurants, cafes, and modern loft spaces.',
    price: 28000,
    categoryId: 'chandeliers',
    category: getCategory('chandeliers'),
    images: [
      'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'Wrought Iron',
      'Finish': 'Matte Black',
      'Bulb Type': 'E27 x 8',
      'Diameter': '90cm',
      'Height': '45cm',
    },
    stock: 6,
    lowStockThreshold: 2,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // LED CEILING LIGHTS (8 products)
  {
    id: 'led-001',
    sku: 'NJE-LED-001',
    name: 'LED Panel Light 60x60cm 48W',
    slug: 'led-panel-light-60x60cm-48w',
    description: 'Professional 60x60cm LED panel light with 48W power output. Daylight white, flicker-free, perfect for offices, schools, and commercial spaces.',
    price: 3500,
    compareAtPrice: 4500,
    categoryId: 'led-ceiling-lights',
    category: getCategory('led-ceiling-lights'),
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Wattage': '48W',
      'Voltage': '220-240V AC',
      'Color Temperature': '6500K (Daylight)',
      'Lumens': '4800lm',
      'Size': '600mm x 600mm',
      'Lifespan': '50,000 hours',
    },
    stock: 50,
    lowStockThreshold: 10,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'led-002',
    sku: 'NJE-LED-002',
    name: 'LED Ceiling Light Round 24W',
    slug: 'led-ceiling-light-round-24w',
    description: 'Modern round LED ceiling light with 3-color temperature options. Remote controlled, dimmable. Perfect for bedrooms and living rooms.',
    price: 4500,
    categoryId: 'led-ceiling-lights',
    category: getCategory('led-ceiling-lights'),
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Wattage': '24W',
      'Color Temperature': '3000K/4500K/6500K',
      'Diameter': '40cm',
      'Remote Control': 'Included',
      'Dimmable': 'Yes',
    },
    stock: 30,
    lowStockThreshold: 8,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'led-003',
    sku: 'NJE-LED-003',
    name: 'LED Ceiling Light Square 36W',
    slug: 'led-ceiling-light-square-36w',
    description: 'Sleek square LED ceiling light with modern design. High efficiency, even light distribution. Suitable for all room types.',
    price: 5500,
    categoryId: 'led-ceiling-lights',
    category: getCategory('led-ceiling-lights'),
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Wattage': '36W',
      'Color Temperature': '4000K (Neutral)',
      'Size': '45cm x 45cm',
      'Material': 'Aluminum + Acrylic',
      'IP Rating': 'IP20',
    },
    stock: 25,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'led-004',
    sku: 'NJE-LED-004',
    name: 'LED Ceiling Light Flower Design 48W',
    slug: 'led-ceiling-light-flower-design-48w',
    description: 'Decorative LED ceiling light with beautiful flower petal design. Creates stunning ambient lighting effect.',
    price: 8500,
    compareAtPrice: 10000,
    categoryId: 'led-ceiling-lights',
    category: getCategory('led-ceiling-lights'),
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Wattage': '48W',
      'Color Temperature': '3000K-6500K (Adjustable)',
      'Diameter': '55cm',
      'Remote Control': 'Included',
      'App Control': 'Optional WiFi module',
    },
    stock: 12,
    lowStockThreshold: 3,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // SWITCHES (8 products)
  {
    id: 'sw-001',
    sku: 'NJE-SW-001',
    name: 'Smart Touch Switch 3-Gang White',
    slug: 'smart-touch-switch-3-gang-white',
    description: 'Modern tempered glass touch switch with 3 gangs. LED indicator, works with standard wiring. Elegant white finish.',
    price: 2800,
    categoryId: 'switches',
    category: getCategory('switches'),
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Type': 'Touch Switch',
      'Gangs': '3',
      'Voltage': '220-250V AC',
      'Max Load': '600W per gang',
      'Material': 'Tempered Glass',
      'Color': 'White',
    },
    stock: 100,
    lowStockThreshold: 20,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'sw-002',
    sku: 'NJE-SW-002',
    name: 'Smart Touch Switch 2-Gang Black',
    slug: 'smart-touch-switch-2-gang-black',
    description: 'Sleek black tempered glass touch switch. 2 gangs with LED backlight. Modern aesthetic for contemporary homes.',
    price: 2400,
    categoryId: 'switches',
    category: getCategory('switches'),
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Type': 'Touch Switch',
      'Gangs': '2',
      'Voltage': '220-250V AC',
      'Material': 'Tempered Glass',
      'Color': 'Black',
    },
    stock: 80,
    lowStockThreshold: 15,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'sw-003',
    sku: 'NJE-SW-003',
    name: 'Classic Wall Switch 4-Gang',
    slug: 'classic-wall-switch-4-gang',
    description: 'Traditional 4-gang wall switch with rocker design. Durable ABS plastic construction. Reliable and affordable.',
    price: 450,
    categoryId: 'switches',
    category: getCategory('switches'),
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Type': 'Rocker Switch',
      'Gangs': '4',
      'Voltage': '220-250V AC',
      'Max Load': '10A per gang',
      'Material': 'ABS Plastic',
    },
    stock: 200,
    lowStockThreshold: 50,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'sw-004',
    sku: 'NJE-SW-004',
    name: 'Dimmer Switch 1-Gang',
    slug: 'dimmer-switch-1-gang',
    description: 'Rotary dimmer switch for incandescent and dimmable LED bulbs. Smooth brightness control from 0-100%.',
    price: 1800,
    categoryId: 'switches',
    category: getCategory('switches'),
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Type': 'Rotary Dimmer',
      'Voltage': '220-250V AC',
      'Max Load': '300W LED / 600W Incandescent',
      'Material': 'PC Plastic',
    },
    stock: 45,
    lowStockThreshold: 10,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // SOLAR FLOODLIGHTS (6 products)
  {
    id: 'sf-001',
    sku: 'NJE-SF-001',
    name: 'Solar Floodlight 200W with Remote',
    slug: 'solar-floodlight-200w-with-remote',
    description: 'High-power 200W solar floodlight with remote control. IP66 waterproof, motion sensor, ideal for outdoor security.',
    price: 8500,
    compareAtPrice: 10000,
    categoryId: 'solar-floodlights',
    category: getCategory('solar-floodlights'),
    images: [
      'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Wattage': '200W equivalent',
      'Solar Panel': '25W Polycrystalline',
      'Battery': '25000mAh Lithium',
      'Lumens': '20000lm',
      'IP Rating': 'IP66',
      'Working Time': '8-12 hours',
    },
    stock: 20,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'sf-002',
    sku: 'NJE-SF-002',
    name: 'Solar Floodlight 100W Motion Sensor',
    slug: 'solar-floodlight-100w-motion-sensor',
    description: 'Mid-range solar floodlight with intelligent motion sensor. Auto on/off at dusk. Perfect for compound security.',
    price: 5500,
    categoryId: 'solar-floodlights',
    category: getCategory('solar-floodlights'),
    images: [
      'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Wattage': '100W equivalent',
      'Solar Panel': '15W',
      'Battery': '15000mAh',
      'Motion Sensor': 'Yes (10m range)',
      'IP Rating': 'IP65',
    },
    stock: 35,
    lowStockThreshold: 8,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'sf-003',
    sku: 'NJE-SF-003',
    name: 'Solar Floodlight 50W Budget',
    slug: 'solar-floodlight-50w-budget',
    description: 'Affordable solar floodlight for basic outdoor lighting needs. Easy installation, no wiring required.',
    price: 3500,
    categoryId: 'solar-floodlights',
    category: getCategory('solar-floodlights'),
    images: [
      'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Wattage': '50W equivalent',
      'Solar Panel': '8W',
      'Battery': '6000mAh',
      'IP Rating': 'IP65',
      'Working Time': '6-8 hours',
    },
    stock: 0,
    lowStockThreshold: 10,
    availability: 'OUT_OF_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // EXTENSION CABLES (6 products)
  {
    id: 'ec-001',
    sku: 'NJE-EC-001',
    name: 'Extension Cable 5M Heavy Duty 4-Way',
    slug: 'extension-cable-5m-heavy-duty-4-way',
    description: '5-meter heavy duty extension cable with 4 outlets and surge protection. 13A rated, suitable for heavy appliances.',
    price: 1800,
    categoryId: 'extension-cables',
    category: getCategory('extension-cables'),
    images: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Length': '5 meters',
      'Outlets': '4',
      'Rating': '13A / 3120W',
      'Surge Protection': 'Yes',
      'Cable Type': '3x1.5mm²',
      'Plug Type': 'BS1363 (UK)',
    },
    stock: 60,
    lowStockThreshold: 15,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'ec-002',
    sku: 'NJE-EC-002',
    name: 'Extension Cable 10M Industrial',
    slug: 'extension-cable-10m-industrial',
    description: '10-meter industrial grade extension cable. Extra thick cable for workshops and construction sites.',
    price: 3500,
    categoryId: 'extension-cables',
    category: getCategory('extension-cables'),
    images: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Length': '10 meters',
      'Outlets': '2',
      'Rating': '16A / 3680W',
      'Cable Type': '3x2.5mm²',
      'Material': 'Heavy duty rubber',
    },
    stock: 25,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'ec-003',
    sku: 'NJE-EC-003',
    name: 'Extension Cable 3M USB Power Strip',
    slug: 'extension-cable-3m-usb-power-strip',
    description: 'Modern extension with 4 AC outlets and 4 USB ports. Perfect for office desks and charging stations.',
    price: 2200,
    categoryId: 'extension-cables',
    category: getCategory('extension-cables'),
    images: [
      'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Length': '3 meters',
      'AC Outlets': '4',
      'USB Ports': '4 (5V 2.4A each)',
      'Rating': '10A / 2500W',
      'Surge Protection': 'Yes',
    },
    stock: 40,
    lowStockThreshold: 10,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // ELECTRICAL CABLES (6 products)
  {
    id: 'tc-001',
    sku: 'NJE-TC-001',
    name: 'Twin & Earth Cable 2.5mm 100M',
    slug: 'twin-earth-cable-2-5mm-100m',
    description: '100-meter roll of 2.5mm twin and earth cable. Suitable for power circuits and general wiring in residential buildings.',
    price: 12500,
    categoryId: 'electrical-cables',
    category: getCategory('electrical-cables'),
    images: [
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Size': '2.5mm²',
      'Length': '100 meters',
      'Cores': '3 (Live, Neutral, Earth)',
      'Voltage Rating': '450/750V',
      'Standard': 'BS 6004',
    },
    stock: 30,
    lowStockThreshold: 8,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'tc-002',
    sku: 'NJE-TC-002',
    name: 'Twin & Earth Cable 1.5mm 100M',
    slug: 'twin-earth-cable-1-5mm-100m',
    description: '100-meter roll of 1.5mm twin and earth cable. Ideal for lighting circuits.',
    price: 8500,
    categoryId: 'electrical-cables',
    category: getCategory('electrical-cables'),
    images: [
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Size': '1.5mm²',
      'Length': '100 meters',
      'Cores': '3 (Live, Neutral, Earth)',
      'Voltage Rating': '450/750V',
    },
    stock: 45,
    lowStockThreshold: 10,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'tc-003',
    sku: 'NJE-TC-003',
    name: 'Flexible Cable 3-Core 2.5mm 50M',
    slug: 'flexible-cable-3-core-2-5mm-50m',
    description: '50-meter flexible cable for appliances and temporary installations. High flexibility and durability.',
    price: 7500,
    categoryId: 'electrical-cables',
    category: getCategory('electrical-cables'),
    images: [
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Size': '2.5mm²',
      'Length': '50 meters',
      'Cores': '3',
      'Type': 'Flexible PVC',
    },
    stock: 20,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // WALL BRACKETS (5 products)
  {
    id: 'wb-001',
    sku: 'NJE-WB-001',
    name: 'Modern Wall Bracket Light Gold',
    slug: 'modern-wall-bracket-light-gold',
    description: 'Contemporary wall bracket light with adjustable head. Gold finish adds elegance to bedrooms and hallways.',
    price: 3200,
    categoryId: 'wall-brackets',
    category: getCategory('wall-brackets'),
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'Metal + Fabric Shade',
      'Finish': 'Gold',
      'Bulb Type': 'E27',
      'Max Wattage': '40W',
      'Switch': 'Pull cord',
    },
    stock: 18,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'wb-002',
    sku: 'NJE-WB-002',
    name: 'Crystal Wall Sconce Pair',
    slug: 'crystal-wall-sconce-pair',
    description: 'Elegant crystal wall sconces sold as a pair. Perfect for flanking mirrors, beds, or feature walls.',
    price: 8500,
    categoryId: 'wall-brackets',
    category: getCategory('wall-brackets'),
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'K9 Crystal + Chrome',
      'Quantity': '2 pieces (pair)',
      'Bulb Type': 'E14 x 2 each',
      'Size': '25cm W x 35cm H each',
    },
    stock: 8,
    lowStockThreshold: 2,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'wb-003',
    sku: 'NJE-WB-003',
    name: 'Industrial Pipe Wall Light',
    slug: 'industrial-pipe-wall-light',
    description: 'Rustic industrial-style wall light made from iron pipes. Exposed bulb design for vintage aesthetics.',
    price: 2800,
    categoryId: 'wall-brackets',
    category: getCategory('wall-brackets'),
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'Iron Pipe',
      'Finish': 'Black',
      'Bulb Type': 'E27 (Edison style)',
      'Max Wattage': '60W',
    },
    stock: 22,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // OUTDOOR LIGHTS (5 products)
  {
    id: 'ol-001',
    sku: 'NJE-OL-001',
    name: 'Solar Garden Bollard Light',
    slug: 'solar-garden-bollard-light',
    description: 'Stainless steel solar bollard light for pathways and gardens. Auto on/off with dusk sensor.',
    price: 4500,
    categoryId: 'outdoor-lights',
    category: getCategory('outdoor-lights'),
    images: [
      'https://images.unsplash.com/photo-1558171013-50b41a2e961a?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'Stainless Steel',
      'Height': '60cm',
      'Solar Panel': '1W',
      'LED': '1W warm white',
      'Battery': '1200mAh',
      'IP Rating': 'IP44',
    },
    stock: 35,
    lowStockThreshold: 8,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'ol-002',
    sku: 'NJE-OL-002',
    name: 'Outdoor Wall Lantern Black',
    slug: 'outdoor-wall-lantern-black',
    description: 'Classic outdoor wall lantern with black aluminum body. Weather-resistant for gate posts and porches.',
    price: 3500,
    categoryId: 'outdoor-lights',
    category: getCategory('outdoor-lights'),
    images: [
      'https://images.unsplash.com/photo-1558171013-50b41a2e961a?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Material': 'Aluminum + Glass',
      'Finish': 'Black',
      'Bulb Type': 'E27',
      'Max Wattage': '60W',
      'IP Rating': 'IP44',
    },
    stock: 28,
    lowStockThreshold: 6,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // SOCKETS (5 products)
  {
    id: 'sk-001',
    sku: 'NJE-SK-001',
    name: 'Double Socket 13A Switched',
    slug: 'double-socket-13a-switched',
    description: 'Standard double socket 13A with individual switches. BS1363 compliant with child safety shutters.',
    price: 450,
    categoryId: 'sockets',
    category: getCategory('sockets'),
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Type': 'Double Gang',
      'Rating': '13A / 250V',
      'Switched': 'Yes',
      'Standard': 'BS1363',
      'Safety Shutters': 'Yes',
    },
    stock: 150,
    lowStockThreshold: 30,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'sk-002',
    sku: 'NJE-SK-002',
    name: 'Single Socket 13A USB',
    slug: 'single-socket-13a-usb',
    description: 'Single socket with built-in USB charging ports. Convenient for charging phones and tablets.',
    price: 850,
    categoryId: 'sockets',
    category: getCategory('sockets'),
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Type': 'Single Gang + USB',
      'AC Rating': '13A',
      'USB Ports': '2 x Type-A (5V 2.1A)',
      'Standard': 'BS1363',
    },
    stock: 80,
    lowStockThreshold: 20,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // STRING LIGHTS (4 products)
  {
    id: 'sl-001',
    sku: 'NJE-SL-001',
    name: 'Fairy String Lights 10M LED',
    slug: 'fairy-string-lights-10m-led',
    description: '10-meter LED fairy string lights with 100 LEDs. Multiple modes for decoration and events. Warm white.',
    price: 850,
    categoryId: 'string-lights',
    category: getCategory('string-lights'),
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Length': '10 meters',
      'LEDs': '100',
      'Color': 'Warm White',
      'Modes': '8 lighting modes',
      'Power': 'USB / Battery',
      'IP Rating': 'IP44',
    },
    stock: 60,
    lowStockThreshold: 15,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'sl-002',
    sku: 'NJE-SL-002',
    name: 'Globe String Lights 5M Solar',
    slug: 'globe-string-lights-5m-solar',
    description: 'Solar powered globe string lights. Large G40 bulbs for garden and patio decoration.',
    price: 1800,
    categoryId: 'string-lights',
    category: getCategory('string-lights'),
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Length': '5 meters',
      'Bulbs': '10 x G40',
      'Power': 'Solar',
      'Battery': '1200mAh',
      'IP Rating': 'IP65',
    },
    stock: 25,
    lowStockThreshold: 5,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // MIRROR LIGHTS (4 products)
  {
    id: 'ml-001',
    sku: 'NJE-ML-001',
    name: 'LED Mirror Light 60cm 3-Color',
    slug: 'led-mirror-light-60cm-3-color',
    description: '60cm LED mirror light with 3 color temperatures. Touch switch, anti-fog. Ideal for bathroom vanities.',
    price: 3500,
    categoryId: 'mirror-lights',
    category: getCategory('mirror-lights'),
    images: [
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Length': '60cm',
      'Wattage': '12W',
      'Color Temperature': '3000K/4500K/6500K',
      'IP Rating': 'IP44',
      'Material': 'Aluminum',
    },
    stock: 18,
    lowStockThreshold: 4,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'ml-002',
    sku: 'NJE-ML-002',
    name: 'Hollywood Mirror Light Kit',
    slug: 'hollywood-mirror-light-kit',
    description: 'DIY Hollywood-style mirror light kit with 10 LED bulbs. Dimmable, perfect for makeup vanities.',
    price: 2500,
    categoryId: 'mirror-lights',
    category: getCategory('mirror-lights'),
    images: [
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Bulbs': '10 LED globes',
      'Dimmable': 'Yes',
      'Power': 'USB/Plug',
      'Total Length': '3 meters',
    },
    stock: 30,
    lowStockThreshold: 8,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // RECHARGEABLE LAMPS (4 products)
  {
    id: 'rl-001',
    sku: 'NJE-RL-001',
    name: 'Rechargeable Emergency Lamp LED',
    slug: 'rechargeable-emergency-lamp-led',
    description: 'Portable rechargeable LED lamp with 8 hours battery life. Essential for power outages.',
    price: 1500,
    categoryId: 'rechargeable-lamps',
    category: getCategory('rechargeable-lamps'),
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Battery': '4000mAh Lithium',
      'Runtime': '8 hours (high)',
      'Wattage': '5W',
      'Charging': 'USB-C',
      'Brightness Levels': '3',
    },
    stock: 55,
    lowStockThreshold: 12,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'rl-002',
    sku: 'NJE-RL-002',
    name: 'Desk Lamp LED Rechargeable',
    slug: 'desk-lamp-led-rechargeable',
    description: 'Modern rechargeable desk lamp with flexible neck. Touch control, 3 brightness levels.',
    price: 2200,
    categoryId: 'rechargeable-lamps',
    category: getCategory('rechargeable-lamps'),
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Battery': '2000mAh',
      'Runtime': '6-20 hours',
      'Wattage': '4W',
      'Charging': 'USB',
      'Flexible Arm': 'Yes',
    },
    stock: 35,
    lowStockThreshold: 8,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // LIGHT BULBS (5 products)
  {
    id: 'lb-001',
    sku: 'NJE-LB-001',
    name: 'LED Bulb E27 12W Daylight (10 pack)',
    slug: 'led-bulb-e27-12w-daylight-10-pack',
    description: 'Energy-saving LED bulbs, 12W equivalent to 100W incandescent. Pack of 10 bulbs.',
    price: 2500,
    categoryId: 'bulbs',
    category: getCategory('bulbs'),
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Base': 'E27',
      'Wattage': '12W',
      'Equivalent': '100W incandescent',
      'Color': '6500K Daylight',
      'Lumens': '1200lm',
      'Quantity': '10 bulbs',
    },
    stock: 80,
    lowStockThreshold: 20,
    availability: 'IN_STOCK',
    isFeatured: true,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'lb-002',
    sku: 'NJE-LB-002',
    name: 'LED Bulb E14 5W Warm White (6 pack)',
    slug: 'led-bulb-e14-5w-warm-white-6-pack',
    description: 'Small base LED bulbs for chandeliers and decorative fixtures. Warm white light.',
    price: 1200,
    categoryId: 'bulbs',
    category: getCategory('bulbs'),
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Base': 'E14 (small screw)',
      'Wattage': '5W',
      'Color': '3000K Warm White',
      'Lumens': '500lm',
      'Quantity': '6 bulbs',
    },
    stock: 60,
    lowStockThreshold: 15,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // DOWNLIGHTS (4 products)
  {
    id: 'dl-001',
    sku: 'NJE-DL-001',
    name: 'LED Downlight 7W Recessed White',
    slug: 'led-downlight-7w-recessed-white',
    description: 'Slim recessed LED downlight for false ceilings. 7W high brightness, easy installation.',
    price: 650,
    categoryId: 'downlights',
    category: getCategory('downlights'),
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Wattage': '7W',
      'Cut-out': '90mm',
      'Color': '6500K Daylight',
      'Lumens': '700lm',
      'Beam Angle': '120°',
    },
    stock: 120,
    lowStockThreshold: 25,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'dl-002',
    sku: 'NJE-DL-002',
    name: 'LED Spotlight GU10 5W (4 pack)',
    slug: 'led-spotlight-gu10-5w-4-pack',
    description: 'GU10 LED spotlights for track lights and recessed fixtures. Pack of 4.',
    price: 1200,
    categoryId: 'downlights',
    category: getCategory('downlights'),
    images: [
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Base': 'GU10',
      'Wattage': '5W',
      'Color': '4000K Neutral',
      'Beam Angle': '38°',
      'Quantity': '4 bulbs',
    },
    stock: 50,
    lowStockThreshold: 12,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },

  // CIRCUIT BREAKERS (3 products)
  {
    id: 'cb-001',
    sku: 'NJE-CB-001',
    name: 'MCB Single Pole 20A',
    slug: 'mcb-single-pole-20a',
    description: 'Miniature circuit breaker for electrical panel protection. 20A rated, C curve.',
    price: 350,
    categoryId: 'circuit-breakers',
    category: getCategory('circuit-breakers'),
    images: [
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Rating': '20A',
      'Poles': '1',
      'Breaking Capacity': '6kA',
      'Curve': 'C',
      'Standard': 'IEC 60898',
    },
    stock: 100,
    lowStockThreshold: 25,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'cb-002',
    sku: 'NJE-CB-002',
    name: 'Distribution Board 8-Way',
    slug: 'distribution-board-8-way',
    description: 'Consumer unit with 8 ways for MCBs. Metal enclosure with door.',
    price: 3500,
    categoryId: 'circuit-breakers',
    category: getCategory('circuit-breakers'),
    images: [
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=800&fit=crop',
    ],
    specifications: {
      'Ways': '8',
      'Material': 'Steel',
      'Mounting': 'Surface/Flush',
      'Main Switch': '63A DP',
    },
    stock: 15,
    lowStockThreshold: 4,
    availability: 'IN_STOCK',
    isFeatured: false,
    isActive: true,
    createdAt: '2025-01-02T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
];

// Get featured products
export const getFeaturedProducts = (): Product[] => {
  return mockProducts.filter((p) => p.isFeatured && p.isActive);
};

// Get products by category
export const getProductsByCategory = (categoryId: string): Product[] => {
  return mockProducts.filter((p) => p.categoryId === categoryId && p.isActive);
};

// Get product by slug
export const getProductBySlug = (slug: string): Product | undefined => {
  return mockProducts.find((p) => p.slug === slug && p.isActive);
};

// Get product by ID
export const getProductById = (id: string): Product | undefined => {
  return mockProducts.find((p) => p.id === id && p.isActive);
};

// Export categories from constants
export { CATEGORIES as mockCategories } from '@/constants/categories';
