import type { Category } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: 'chandeliers',
    name: 'Chandeliers',
    slug: 'chandeliers',
    description: 'Elegant chandeliers for homes and businesses',
    icon: '✨',
    productCount: 24,
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'led-ceiling-lights',
    name: 'LED Ceiling Lights',
    slug: 'led-ceiling-lights',
    description: 'Energy-efficient LED ceiling panels and fixtures',
    icon: '💡',
    productCount: 36,
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'switches',
    name: 'Switches',
    slug: 'switches',
    description: 'Modern wall switches and dimmers',
    icon: '🔘',
    productCount: 48,
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'solar-floodlights',
    name: 'Solar Floodlights',
    slug: 'solar-floodlights',
    description: 'Solar-powered outdoor security lights',
    icon: '☀️',
    productCount: 18,
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 'extension-cables',
    name: 'Extension Cables',
    slug: 'extension-cables',
    description: 'Heavy-duty extension cables with surge protection',
    icon: '🔌',
    productCount: 32,
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'electrical-cables',
    name: 'Electrical Cables',
    slug: 'electrical-cables',
    description: 'Quality wiring cables for all applications',
    icon: '⚡',
    productCount: 56,
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 'wall-brackets',
    name: 'Wall Brackets',
    slug: 'wall-brackets',
    description: 'Decorative wall-mounted light fixtures',
    icon: '🏠',
    productCount: 28,
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 'outdoor-lights',
    name: 'Outdoor Lights',
    slug: 'outdoor-lights',
    description: 'Weather-resistant garden and pathway lights',
    icon: '🌙',
    productCount: 22,
    sortOrder: 8,
    isActive: true,
  },
  {
    id: 'sockets',
    name: 'Sockets',
    slug: 'sockets',
    description: 'Wall sockets and power outlets',
    icon: '🔲',
    productCount: 40,
    sortOrder: 9,
    isActive: true,
  },
  {
    id: 'string-lights',
    name: 'String Lights',
    slug: 'string-lights',
    description: 'Decorative fairy lights for events and homes',
    icon: '🎄',
    productCount: 15,
    sortOrder: 10,
    isActive: true,
  },
  {
    id: 'mirror-lights',
    name: 'Mirror Lights',
    slug: 'mirror-lights',
    description: 'Vanity and bathroom mirror lighting',
    icon: '🪞',
    productCount: 12,
    sortOrder: 11,
    isActive: true,
  },
  {
    id: 'rechargeable-lamps',
    name: 'Rechargeable Lamps',
    slug: 'rechargeable-lamps',
    description: 'Portable emergency and desk lamps',
    icon: '🔋',
    productCount: 20,
    sortOrder: 12,
    isActive: true,
  },
  {
    id: 'bulbs',
    name: 'Light Bulbs',
    slug: 'bulbs',
    description: 'LED and energy-saving light bulbs',
    icon: '💡',
    productCount: 45,
    sortOrder: 13,
    isActive: true,
  },
  {
    id: 'circuit-breakers',
    name: 'Circuit Breakers',
    slug: 'circuit-breakers',
    description: 'MCBs, RCCBs and distribution boards',
    icon: '⚡',
    productCount: 35,
    sortOrder: 14,
    isActive: true,
  },
  {
    id: 'doorbells',
    name: 'Doorbells',
    slug: 'doorbells',
    description: 'Wired and wireless doorbell systems',
    icon: '🔔',
    productCount: 14,
    sortOrder: 15,
    isActive: true,
  },
  {
    id: 'security-cameras',
    name: 'Security Cameras',
    slug: 'security-cameras',
    description: 'CCTV and smart security solutions',
    icon: '📹',
    productCount: 25,
    sortOrder: 16,
    isActive: true,
  },
  {
    id: 'fans',
    name: 'Ceiling Fans',
    slug: 'fans',
    description: 'Ceiling and exhaust fans',
    icon: '🌀',
    productCount: 18,
    sortOrder: 17,
    isActive: true,
  },
  {
    id: 'downlights',
    name: 'Downlights',
    slug: 'downlights',
    description: 'Recessed LED downlights and spotlights',
    icon: '🔦',
    productCount: 30,
    sortOrder: 18,
    isActive: true,
  },
  {
    id: 'trunking',
    name: 'Trunking & Conduits',
    slug: 'trunking',
    description: 'Cable management systems',
    icon: '📦',
    productCount: 22,
    sortOrder: 19,
    isActive: true,
  },
  {
    id: 'transformers',
    name: 'Transformers',
    slug: 'transformers',
    description: 'Voltage stabilizers and transformers',
    icon: '🔌',
    productCount: 16,
    sortOrder: 20,
    isActive: true,
  },
  {
    id: 'smart-home',
    name: 'Smart Home',
    slug: 'smart-home',
    description: 'WiFi switches, plugs and automation',
    icon: '📱',
    productCount: 20,
    sortOrder: 21,
    isActive: true,
  },
];

export const getCategoryById = (id: string): Category | undefined => {
  return CATEGORIES.find((cat) => cat.id === id);
};

export const getCategoryBySlug = (slug: string): Category | undefined => {
  return CATEGORIES.find((cat) => cat.slug === slug);
};
